name: Auto Update Archive

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 新增这一步：安装 Python 依赖
      - name: Install dependencies
        run: pip install jinja2  # 只需要这一条命令，安装你需要的库

      - name: Run generation scripts
        run: |
          python generate_archive.py
          python generate_index.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add archive.html index.html
          git commit -m "CI: Auto-update lists [skip actions]" || echo "No changes to commit"
          git push