name: Auto Update Archive

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # 明确指定你的Python版本

      - name: Run generation scripts
        run: |
          python generate_archive.py
          python generate_index.py  # 新增这一行，运行新的主页生成脚本

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add archive.html index.html
          git commit -m "CI: Auto-update archive list [skip actions]" || echo "No changes to commit"
          git push